debug: true

server:
  port: 8080
#  servlet:
#    context-path: /elmqx/

spring:
  datasource:
    # 返回影响的行数，设置时区为【上海】
    url:               jdbc:mysql://47.94.5.149:3306/elmqx?useAffectedRows=true&serverTimezone=Asia/Shanghai
    username:          elmqx_dev
    password:          elmpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    type:              com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池配置
      initial-size:                              5
      min-idle:                                  5
      max-wait:                                  60000
      max-active:                                20
      timeBetweenEvictionRunsMillis:             60000
      minEvictableIdleTimeMillis:                300000
      validationQuery:                           SELECT 1 FROM DUAL
      testWhileIdle:                             true
      testOnBorrow:                              false
      testOnReturn:                              false
      poolPreparedStatements:                    true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat:                   true
      # 监控配置
      web-stat-filter:
        enabled:        true
        url-pattern:    /*
        exclusions:     /druid/*,*.js,*.css,*.html,*.png,*.ico,*.gif,*.jpg
        profile-enable: true
        session-stat-enable: true
      stat-view-servlet:
        # 配置监控页面访问密码
        login-password: druidAdmin
        login-username: admin
        # url
        url-pattern:    /druid/*
        # 启用重置计数器
        reset-enable:   true
        enabled:        true
        allow:
      filter:
        # sql 监控
        stat:
          enabled: true
        # 防火墙
        wall:
          enabled: true
      # spring aop 监控，多个使用 , 分开
      aop-patterns:
        com.xcphoenix.dto.mapper.*,com.xcphoenix.dto.service.*

  # redis cache
  redis:
    host: 47.94.5.149
    database: 1

  # elasticsearch
  elasticsearch:
    jest:
      uris: http://47.94.5.149:9200
  
  # quartz
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_
#            isClustered: true
#            clusterCheckinInterval: 10000
#            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
#    #数据库方式
#    job-store-type: jdbc
#    #初始化表结构
#    jdbc:
#      initialize-schema: never

  profiles:
    active: local-dev

# mybatis
mybatis:
#  configuration:
#    # 开启驼峰命名
#    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  
# log
logging.file: "logs/dto.log"
logging:
  file:
    max-size: 10MB
    max-history: 20
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} :: %clr(%-40.40logger{39}){cyan} {N:%line} %clr(>>){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } > [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    
---

upload:
  url: "http://localhost:8080/images/"
  path: "/home/xuanc/桌面/DtoProject/back-end/images/"

spring:
  profiles: local-dev
  
---

upload:
  url: "http://47.94.5.149:8080/images/"
  path: "/root/project/springboot/dto/images/"

spring:
  profiles: server-dev
